export const DOWNLOAD_VID='DOWNLOAD_VID';
export const LOADING_VID='LOADING_VID';
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const HISTORY_LOADING='HISTORY_LOADING';
export const HISTORY_LOADED='HISTORY_LOADED';
export const HISTORY_DELETED='HISTORY_DELETED';
export const SEARCH_HISTORY='SEARCH_HISTORY';
export const LOADING_PLAYLIST='LOADING_PLAYLIST';
export const PLAYLIST_LOADED='PLAYLIST_LOADED';


